# https://docs.github.com/en/actions/learn-github-actions/contexts

---
name: Gittyup
on:
  push:
    branches:
    - master
  pull_request:
  page_build:
  workflow_dispatch:

env:
  IS_RELEASE: ${{ github.event_name == 'push' && github.ref_type == 'tag' && startswith(github.ref_name, 'gittyup_v') }}

jobs:
  appimage:
    name: AppImage
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build AppImage
      run: |
        ../appimage-builder/build.sh
